### Request Passport
POST http://localhost:8000/api/auth/passport
Content-Type: application/json

{
  "email": "bob.doe@storagie.com"
}


### Validate Passport
POST http://localhost:8000/api/auth/validate
Content-Type: application/json

{
  "passport": "cmaonaaok00019ydykt9ocq2j"
}


### Refresh Token
PATCH http://localhost:8000/api/auth/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWFvZ3JzdDYwMDAwOXkzbTZja3ExemtuIiwiZW1haWwiOiJib2IuZG9lQHN0b3JhZ2llLmNvbSIsInJvbGUiOiJVU0VSIiwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTc0NzI2OTc1MywiZXhwIjoxNzQ3MjY5ODEzfQ.S2B_63I-7qcOVIIAtbEhUxRPhmfHcn6H7E51a2fvsas

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWFvZ3JzdDYwMDAwOXkzbTZja3ExemtuIiwic2Vzc2lvbklkIjoiY21hb25hcWswMDAwMzl5ZHk3N3MwM3Q3bCIsInR5cGUiOiJyZWZyZXNoIiwiaWF0IjoxNzQ3MjY5NzUzLCJleHAiOjE3NDczNTYxNTN9.QJNE2VhQ2agzEc3E9wnVx9lG2lb652vBizVdZkOmFGk"
}
