### Request Passport
POST http://localhost:8000/api/auth/passport
Content-Type: application/json

{
  "email": "bob.doe@storagie.com"
}


### Validate Passport
POST http://localhost:8000/api/auth/validate
Content-Type: application/json

{
  "passport": "cmaozvuhb00099y0artj16vx7"
}


### Refresh Token
PATCH http://localhost:8000/api/auth/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWFvZ3JzdDYwMDAwOXkzbTZja3ExemtuIiwiZW1haWwiOiJib2IuZG9lQHN0b3JhZ2llLmNvbSIsInJvbGUiOiJVU0VSIiwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTc0NzI5MDkyMywiZXhwIjoxNzQ3MjkwOTgzfQ.vRhaRAPMstAxjcIO4xw6L-76dTTB9vof6ZuNMzB-T_M

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWFvZ3JzdDYwMDAwOXkzbTZja3ExemtuIiwic2Vzc2lvbklkIjoiY21hb3p3Z3RwMDAwYjl5MGFvOTkxcXk2eCIsInR5cGUiOiJyZWZyZXNoIiwiaWF0IjoxNzQ3MjkwOTIzLCJleHAiOjE3NDczNzczMjN9.g1Dy6gor6P_4HhLFU8G79eRvKQpLPGoX4FQ3WURIqac"
}
